-- ========================================
-- INSERTAR PLANES DE PRECIO (6 registros)
-- ========================================

INSERT INTO pricing_plans (id, plan_id, name, description, price, price_display, currency, interval, features, tier, interactions_limit, is_annual, discount, popular, available, stripe_product_id, stripe_price_id, created_at, updated_at) VALUES
(38, 'free', 'Free', 'Plan gratuito con funciones básicas, Ideal para probar la plataforma.', 0, '$0/mes', 'cad', 'month', '["5 conversaciones AI/mes","✅ 1 integración web básica","✅ 1 formulario simple (máx 3 campos)","✅ Dashboard básico","✅ Soporte por email","✅ Personalización limitada (3 colores predefinidos)","❌ Sin emails automatizados","❌ Sin procesamiento documentos","❌ Sin IA avanzada"]', 'free', 10, FALSE, NULL, FALSE, TRUE, 'prod_SzMNXRTPqqJkb9', 'price_1S3Nf6BXZVMfAIDGCbmVHiN5', '2025-09-03 10:38:36.109423', '2025-09-12 18:31:28.316'),

(39, 'pro', 'Pro', 'Plan profesional para empresas', 1700, '$17/mes', 'CAD', 'month', '["✅ 200 conversaciones AI/mes","✅ 5 integraciones web completas","✅ 5 formularios avanzados (campos ilimitados)","✅ 50 emails automatizados/mes (confirmaciones, notificaciones)","✅ 15 documentos procesados/mes (PDF/Word)","✅ IA avanzada: análisis sentimiento + resúmenes","✅ Personalización completa (colores, fuentes, logos)","✅ API propia con key personalizada","✅ Exportación CSV/PDF","✅ Soporte prioritario","✅ Webhooks básicos","✅ Historial 30 días"]', 'pro', 400, FALSE, NULL, TRUE, TRUE, 'prod_SzMOWan7x1wdfi', 'price_1S3NfKBXZVMfAIDGzs0qSCyi', '2025-09-03 10:38:36.109423', '2025-09-12 18:52:16.706'),

(40, 'enterprise', 'Enterprise', 'Plan empresarial con funciones avanzadas', 7700, '$77/mes', 'cad', 'month', '["1,000 conversaciones AI/mes","✅ Integraciones ILIMITAD","✅ Formularios ILIMITADOS + plantillas premium","✅ 50 documentos procesados/mes","✅ IA empresarial: sentimiento + resumen + generación automática","✅ Brand completo: personalización total","✅ APIs múltiples + webhooks avanzados","✅ Roles de usuario + administración multiusuario","✅ Exportación masiva (CSV/PDF/JSON)","✅ Soporte dedicado + onboarding personalizado","✅ Historial ILIMITADO","✅ Backup automático"]', 'enterprise', 2000, FALSE, NULL, FALSE, TRUE, 'stripe_not_configured', 'stripe_not_configured', '2025-09-03 10:38:36.109423', '2025-09-12 19:04:34.649'),

(42, 'free_annual', 'Free', 'Plan gratuito anual para probar la plataforma', 0, '$0/año', 'CAD', 'year', '["5 conversaciones AI/mes","✅ 1 integración web básica","✅ 1 formulario simple (máx 3 campos)","✅ Dashboard básico","✅ Soporte por email","✅ Personalización limitada (3 colores predefinidos)","❌ Sin emails automatizados","❌ Sin procesamiento documentos","❌ Sin IA avanzada"]', 'free', 20, TRUE, NULL, FALSE, TRUE, 'stripe_not_configured', 'stripe_not_configured', '2025-09-12 18:07:46.4936', '2025-09-12 18:33:07.858'),

(43, 'pro_annual', 'Pro', 'Plan profesional anual para empresas con descuento', 17000, '$170/año', 'CAD', 'year', '["✅ 200 conversaciones AI/mes","✅ 5 integraciones web completas","✅ 5 formularios avanzados (campos ilimitados)","✅ 50 emails automatizados/mes (confirmaciones, notificaciones)","✅ 15 documentos procesados/mes (PDF/Word)","✅ IA avanzada: análisis sentimiento + resúmenes","✅ Personalización completa (colores, fuentes, logos)","✅ API propia con key personalizada","✅ Exportación CSV/PDF","✅ Soporte prioritario","✅ Webhooks básicos","✅ Historial 30 días"]', 'pro', 2400, TRUE, NULL, TRUE, TRUE, 'stripe_not_configured', 'stripe_not_configured', '2025-09-12 18:07:49.056063', '2025-09-12 18:52:28.954'),

(44, 'enterprise_annual', 'Enterprise', 'Plan empresarial anual con descuento y funciones completas', 77000, '$770/año', 'CAD', 'year', '["1,000 conversaciones AI/mes","✅ Integraciones ILIMITAD","✅ Formularios ILIMITADOS + plantillas premium","✅ 300 emails automatizados/mes","✅ 50 documentos procesados/mes","✅ IA empresarial: sentimiento + resumen + generación automática","✅ Brand completo: personalización total","✅ APIs múltiples + webhooks avanzados","✅ Roles de usuario + administración multiusuario","✅ Exportación masiva (CSV/PDF/JSON)","✅ Soporte dedicado + onboarding personalizado","✅ Historial ILIMITADO","✅ Backup automático"]', 'enterprise', 2000, TRUE, NULL, FALSE, TRUE, 'stripe_not_configured', 'stripe_not_configured', '2025-09-12 18:07:52.66651', '2025-09-12 19:04:41.268');

-- Actualizar secuencia
SELECT setval('pricing_plans_id_seq', (SELECT MAX(id) FROM pricing_plans));